[project]
name = "beavers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pettingzoo>=1.25.0",
    "pygame>=2.6.1",
    "pymunk>=7.1.0",
]
