[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "core",
    "render",
]

[tool.uv.sources]
render = { workspace = true }
core = { workspace = true }

