[package]
name = "castor-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
default-run = "castor-cli"

[dependencies]
bevy = "0.17.2"
rand = "0.9.2"
rand_chacha = "0.9.0"
